"""regenerate

Revision ID: 41ec7fb01b3e
Revises: 17945fc69ef2
Create Date: 2026-03-10 03:11:05.457478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41ec7fb01b3e'
down_revision: Union[str, Sequence[str], None] = '17945fc69ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('menu_item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('cart_items', sa.Column('restaurant_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'cart_items', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('cart_items', 'created_at')
    op.drop_column('cart_items', 'special_instructions')
    op.drop_column('cart_items', 'updated_at')
    op.drop_constraint(op.f('carts_user_id_key'), 'carts', type_='unique')
    op.drop_constraint(op.f('carts_restaurant_id_fkey'), 'carts', type_='foreignkey')
    op.drop_column('carts', 'restaurant_id')
    op.drop_column('carts', 'updated_at')
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=False))
    op.drop_constraint(op.f('orders_cart_id_key'), 'orders', type_='unique')
    op.drop_constraint(op.f('orders_cart_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'cart_id')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_cart_id_fkey'), 'orders', 'carts', ['cart_id'], ['id'])
    op.create_unique_constraint(op.f('orders_cart_id_key'), 'orders', ['cart_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'user_id')
    op.add_column('carts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('restaurant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('carts_restaurant_id_fkey'), 'carts', 'restaurants', ['restaurant_id'], ['id'])
    op.create_unique_constraint(op.f('carts_user_id_key'), 'carts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.add_column('cart_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('special_instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'restaurant_id')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
