"""Remove nullabvle from reviews

Revision ID: 5dbc6de30c0a
Revises: baeacdcf51cc
Create Date: 2026-03-12 05:42:12.948426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbc6de30c0a'
down_revision: Union[str, Sequence[str], None] = 'baeacdcf51cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
