"""make_owner_id_unique

Revision ID: 9bc1c7dbcbb5
Revises: c083a8521a6a
Create Date: 2026-03-26 09:12:27.228527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc1c7dbcbb5'
down_revision: Union[str, Sequence[str], None] = 'c083a8521a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'restaurants', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='unique')
    # ### end Alembic commands ###
