"""Add field order_id for review

Revision ID: baeacdcf51cc
Revises: de59a0e2c146
Create Date: 2026-03-12 05:36:35.684673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baeacdcf51cc'
down_revision: Union[str, Sequence[str], None] = 'de59a0e2c146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('order_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'reviews', ['order_id'])
    op.create_foreign_key(None, 'reviews', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'order_id')
    # ### end Alembic commands ###
