"""Add rider section

Revision ID: bf8a958b21fc
Revises: c2b81d33e8fd
Create Date: 2026-03-26 04:40:31.298190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8a958b21fc'
down_revision: Union[str, Sequence[str], None] = 'c2b81d33e8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rider_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['rider_id'], ['id'])
    op.add_column('users', sa.Column('vehicle_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_available')
    op.drop_column('users', 'vehicle_type')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'rider_id')
    # ### end Alembic commands ###
